name: run mixer
  
on:
  schedule:
    - cron: "*/5 * * * *"
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Bash script
        run: |
          chmod +x mixer.sh
          ./mixer.sh

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update configs"
          git push
